name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama que uses para tu desarrollo, si es diferente.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usa una m치quina virtual con Ubuntu

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Clona el repositorio

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Usa la versi칩n de Python que prefieras

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs ghp-import  # Instala MkDocs y ghp-import para el deploy

    - name: Build documentation
      run: |
        mkdocs build  # Construye la documentaci칩n est치tica

    - name: Set up Git for GitHub Actions
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Deploy to GitHub Pages
      run: |
        git remote set-url origin https://github.com/${{ github.repository }}.git
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push https://x-access-token:${{ secrets.MY_DEPLOY_TOKEN }}@github.com/${{ github.repository }} gh-pages --force  # Usa el PAT en lugar de GITHUB_TOKEN
