name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esta rama por la que estés usando para desarrollo, si es necesario

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main  # Usa la rama desde la que estás haciendo el despliegue

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Build the project
        run: |
          # Aquí agregas los comandos para compilar tu proyecto si es necesario.
          # Ejemplo: npm install && npm run build
          echo "Build your project here"

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Usa tu token de acceso personal
        run: |
          git remote set-url origin https://github.com/3dsmanual/3dsmanual.github.io.git
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push https://$GH_TOKEN@github.com/3dsmanual/3dsmanual.github.io.git gh-pages --force
