name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the site
        run: |
          mkdocs build

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check if gh-pages exists
        run: |
          git fetch origin
          git branch -r | grep -q 'origin/gh-pages' || git checkout --orphan gh-pages

      - name: Add files for deployment
        run: |
          git add -A site/
          git status

      - name: Commit files
        run: |
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://github.com/3dsmanual/3dsmanual.github.io.git
          git push https://$GH_TOKEN@github.com/3dsmanual/3dsmanual.github.io.git gh-pages --force
